// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Discord Login

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_LoginScreen
void ui_LoginScreen_screen_init(void);
lv_obj_t * ui_LoginScreen;
lv_obj_t * ui_Header_Panel;
lv_obj_t * ui_Header_Text;
lv_obj_t * ui_Discord_Icon;
lv_obj_t * ui_CredentialsForm;
lv_obj_t * ui_EmailOrPhoneInput;
lv_obj_t * ui_Label;
lv_obj_t * ui_Required_Label;
void ui_event_TextArea(lv_event_t * e);
lv_obj_t * ui_TextArea;
lv_obj_t * ui_PassworInput;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Required_Label1;
void ui_event_TextArea1(lv_event_t * e);
lv_obj_t * ui_TextArea1;
void ui_event_Forgot_Password_Button(lv_event_t * e);
lv_obj_t * ui_Forgot_Password_Button;
lv_obj_t * ui_Forgot_Password;
void ui_event_ButtonSend(lv_event_t * e);
lv_obj_t * ui_ButtonSend;
lv_obj_t * ui_Label3;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_TextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        LoadKeyboard(e);
    }
}
void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        LoadKeyboard(e);
    }
}
void ui_event_Forgot_Password_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ForgotPassword(e);
    }
}

void ui_event_ButtonSend(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        SendForm(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_LoginScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_LoginScreen);
}
