// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Setting

#ifndef _SETTING_UI_H
#define _SETTING_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Setting
void ui_Setting_screen_init(void);
extern lv_obj_t * ui_Setting;
extern lv_obj_t * ui_Label3;
// SCREEN: ui_Setting1
void ui_Setting1_screen_init(void);
extern lv_obj_t * ui_Setting1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_364238874);    // assets/icons8-wifi-48.png



LV_FONT_DECLARE(ui_font_gg_sans_bold);
LV_FONT_DECLARE(ui_font_gg_sans_small);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
