// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Discord Login

#include "ui.h"

void LoadKeyboard(lv_event_t * e)
{
	// Your code here
}

void ForgotPassword(lv_event_t * e)
{
	// Your code here
}

void SendForm(lv_event_t * e)
{
	// Your code here
}
