// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Discord Login

#ifndef _DISCORD_LOGIN_UI_H
#define _DISCORD_LOGIN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui/ui_helpers.h"
#include "ui/ui_events.h"

// SCREEN: ui_LoginScreen
void ui_LoginScreen_screen_init(void);

extern lv_obj_t * ui_LoginScreen;
extern lv_obj_t * ui_Header_Panel;
extern lv_obj_t * ui_Header_Text;
extern lv_obj_t * ui_Discord_Icon;
extern lv_obj_t * ui_CredentialsForm;
extern lv_obj_t * ui_EmailOrPhoneInput;
extern lv_obj_t * ui_Label;
extern lv_obj_t * ui_Required_Label;
void ui_event_TextArea(lv_event_t * e);
extern lv_obj_t * ui_TextArea;
extern lv_obj_t * ui_PassworInput;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Required_Label1;
extern lv_obj_t * ui_TextArea1;
void ui_event_Forgot_Password_Button(lv_event_t * e);
extern lv_obj_t * ui_Forgot_Password_Button;
extern lv_obj_t * ui_Forgot_Password;
void ui_event_ButtonSend(lv_event_t * e);
extern lv_obj_t * ui_ButtonSend;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_discord_com_login_normal_png);    // assets/discord.com_login_normal.png

LV_FONT_DECLARE(ui_font_gg_sans_bold);
LV_FONT_DECLARE(ui_font_gg_sans_small);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
