// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Discord Login

#ifndef _DISCORD_LOGIN_UI_H
#define _DISCORD_LOGIN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void KeyboardShow_Animation(lv_obj_t * TargetObject, int delay);
void KeyboardHide_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_BotKeyScreen
void ui_BotKeyScreen_screen_init(void);
extern lv_obj_t * ui_BotKeyScreen;
extern lv_obj_t * ui_Right_Panel;
extern lv_obj_t * ui_QrCode;
extern lv_obj_t * ui_Left_Panel;
extern lv_obj_t * ui_Header_Text;
extern lv_obj_t * ui_Discord_Icon;
extern lv_obj_t * ui_Info_Text;
extern lv_obj_t * ui_Text_1;
extern lv_obj_t * ui_Text_2;
extern lv_obj_t * ui_Text_3;
extern lv_obj_t * ui_GettingInfoPanel;
extern lv_obj_t * ui_Loading_Text;
extern lv_obj_t * ui_Spinner;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1102433829);    // assets/discord.local-qrcode-img.png
LV_IMG_DECLARE(ui_img_discord_com_login_normal_png);    // assets/discord.com_login_normal.png



LV_FONT_DECLARE(ui_font_gg_sans_bold);
LV_FONT_DECLARE(ui_font_gg_sans_small);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
