// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Discord Login
#include "ui/ui.h"
#include <scripts/SettingController/SettingController.h>
#include <corgi_framwork/SceneManager.h>
#include <corgi_framwork/Script.h>

void WiFiTurnOn(lv_event_t * e)
{
	SettingController* SettingScript = SceneManager::currentScene->getScriptByType<SettingController>();

	if (SettingScript != nullptr)
		SettingScript->WiFiTurnedOn();
}

void WiFiTurnOff(lv_event_t * e)
{
	SettingController* SettingScript = SceneManager::currentScene->getScriptByType<SettingController>();

	if (SettingScript != nullptr)
		SettingScript->WiFiTurnedOff();
}