// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Discord Login

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void LoadKeyboard(lv_event_t * e);
void ForgotPassword(lv_event_t * e);
void SendForm(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
