// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Discord Login

#include "ui/ui.h"

void LoadKeyboard(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);

    lv_obj_t *ta = lv_event_get_target(e);

    if (code == LV_EVENT_CLICKED || code == LV_EVENT_FOCUSED)
    {
        /*Focus on the clicked text area*/
        // if (kb != NULL)
        //     lv_keyboard_set_textarea(kb, ta);
    }
    else if (code == LV_EVENT_READY)
    {
        static const char *btns[] = {"Ok", ""};

        lv_obj_t *MsgBox = lv_msgbox_create(NULL, "Text", lv_textarea_get_text(ta), btns, true);
        lv_obj_center(MsgBox);
    }
}

void ForgotPassword(lv_event_t *e)
{
    lv_obj_t *MsgBox = lv_msgbox_create(NULL, "Not Implemented", "Sorry, but in this device we dont support this action", NULL, true);
    lv_obj_center(MsgBox);
}

void SendForm(lv_event_t *e)
{
}