// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Discord Login

#include "ui/ui.h"

void ui_LoginScreen_screen_init(void)
{
    ui_LoginScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LoginScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LoginScreen, lv_color_hex(0x313338), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoginScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Header_Panel = lv_obj_create(ui_LoginScreen);
    lv_obj_set_width(ui_Header_Panel, lv_pct(40));
    lv_obj_set_height(ui_Header_Panel, lv_pct(100));
    lv_obj_set_align(ui_Header_Panel, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Header_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Header_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Header_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Header_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Header_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Header_Text = lv_label_create(ui_Header_Panel);
    lv_obj_set_width(ui_Header_Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Header_Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Header_Text, 0);
    lv_obj_set_y(ui_Header_Text, 5);
    lv_obj_set_align(ui_Header_Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Header_Text, "Welcom Back!");
    lv_obj_set_style_text_color(ui_Header_Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Header_Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Header_Text, &ui_font_gg_sans_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Discord_Icon = lv_img_create(ui_Header_Panel);
    lv_img_set_src(ui_Discord_Icon, &ui_img_discord_com_login_normal_png);
    lv_obj_set_width(ui_Discord_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Discord_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Discord_Icon, 0);
    lv_obj_set_y(ui_Discord_Icon, -30);
    lv_obj_set_align(ui_Discord_Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Discord_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Discord_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CredentialsForm = lv_obj_create(ui_LoginScreen);
    lv_obj_set_width(ui_CredentialsForm, lv_pct(60));
    lv_obj_set_height(ui_CredentialsForm, lv_pct(100));
    lv_obj_set_align(ui_CredentialsForm, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_CredentialsForm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CredentialsForm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CredentialsForm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CredentialsForm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CredentialsForm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EmailOrPhoneInput = lv_obj_create(ui_CredentialsForm);
    lv_obj_set_height(ui_EmailOrPhoneInput, 73);
    lv_obj_set_width(ui_EmailOrPhoneInput, lv_pct(113));
    lv_obj_set_x(ui_EmailOrPhoneInput, 1);
    lv_obj_set_y(ui_EmailOrPhoneInput, -12);
    lv_obj_set_align(ui_EmailOrPhoneInput, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_EmailOrPhoneInput, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EmailOrPhoneInput, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EmailOrPhoneInput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_EmailOrPhoneInput, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EmailOrPhoneInput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label = lv_label_create(ui_EmailOrPhoneInput);
    lv_obj_set_width(ui_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label, -5);
    lv_obj_set_y(ui_Label, -13);
    lv_label_set_text(ui_Label, "EMAIL OR PHONE NUMBER");
    lv_obj_set_style_text_color(ui_Label, lv_color_hex(0xDBDEE1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label, &ui_font_gg_sans_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Required_Label = lv_label_create(ui_EmailOrPhoneInput);
    lv_obj_set_width(ui_Required_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Required_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Required_Label, 152);
    lv_obj_set_y(ui_Required_Label, -15);
    lv_label_set_text(ui_Required_Label, "*");
    lv_obj_set_style_text_color(ui_Required_Label, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Required_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Required_Label, &ui_font_gg_sans_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea = lv_textarea_create(ui_EmailOrPhoneInput);
    lv_obj_set_width(ui_TextArea, lv_pct(105));
    lv_obj_set_height(ui_TextArea, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_TextArea, -6);
    lv_obj_set_y(ui_TextArea, 12);
    lv_obj_set_align(ui_TextArea, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea, 30);
    lv_textarea_set_one_line(ui_TextArea, true);
    lv_obj_set_style_text_color(ui_TextArea, lv_color_hex(0xB5BAC1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TextArea, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea, lv_color_hex(0x1E1F22), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_textarea_set_text(ui_TextArea, "");
    lv_textarea_set_password_mode(ui_TextArea, false);

    ui_PassworInput = lv_obj_create(ui_CredentialsForm);
    lv_obj_set_height(ui_PassworInput, 85);
    lv_obj_set_width(ui_PassworInput, lv_pct(113));
    lv_obj_set_x(ui_PassworInput, 0);
    lv_obj_set_y(ui_PassworInput, 65);
    lv_obj_set_align(ui_PassworInput, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PassworInput, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PassworInput, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PassworInput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PassworInput, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PassworInput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_PassworInput);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -5);
    lv_obj_set_y(ui_Label1, -13);
    lv_label_set_text(ui_Label1, "PASSWORD");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xDBDEE1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_gg_sans_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Required_Label1 = lv_label_create(ui_PassworInput);
    lv_obj_set_width(ui_Required_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Required_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Required_Label1, 62);
    lv_obj_set_y(ui_Required_Label1, -15);
    lv_label_set_text(ui_Required_Label1, "*");
    lv_obj_set_style_text_color(ui_Required_Label1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Required_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Required_Label1, &ui_font_gg_sans_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_PassworInput);
    lv_obj_set_width(ui_TextArea1, lv_pct(105));
    lv_obj_set_height(ui_TextArea1, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_TextArea1, -6);
    lv_obj_set_y(ui_TextArea1, 4);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea1, 30);
    lv_textarea_set_one_line(ui_TextArea1, true);
    lv_obj_set_style_text_color(ui_TextArea1, lv_color_hex(0xB5BAC1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TextArea1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea1, lv_color_hex(0x1E1F22), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_textarea_set_text(ui_TextArea1, "");
    lv_textarea_set_password_mode(ui_TextArea1, true);

    ui_Forgot_Password_Button = lv_btn_create(ui_PassworInput);
    lv_obj_set_width(ui_Forgot_Password_Button, 129);
    lv_obj_set_height(ui_Forgot_Password_Button, 21);
    lv_obj_set_x(ui_Forgot_Password_Button, -84);
    lv_obj_set_y(ui_Forgot_Password_Button, 35);
    lv_obj_set_align(ui_Forgot_Password_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Forgot_Password_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Forgot_Password_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Forgot_Password_Button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Forgot_Password_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Forgot_Password_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Forgot_Password_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Forgot_Password = lv_label_create(ui_Forgot_Password_Button);
    lv_obj_set_width(ui_Forgot_Password, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Forgot_Password, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Forgot_Password, 0);
    lv_obj_set_y(ui_Forgot_Password, -1);
    lv_obj_set_align(ui_Forgot_Password, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Forgot_Password, "Forgot Your Password?");
    lv_obj_set_style_text_color(ui_Forgot_Password, lv_color_hex(0x00A8FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Forgot_Password, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Forgot_Password, &ui_font_gg_sans_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSend = lv_btn_create(ui_CredentialsForm);
    lv_obj_set_height(ui_ButtonSend, 32);
    lv_obj_set_width(ui_ButtonSend, lv_pct(100));
    lv_obj_set_x(ui_ButtonSend, 0);
    lv_obj_set_y(ui_ButtonSend, 165);
    lv_obj_set_align(ui_ButtonSend, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ButtonSend, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSend, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonSend, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonSend, lv_color_hex(0x5865F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonSend, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonSend, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonSend, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_ButtonSend);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Login");
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_gg_sans_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TextArea, ui_event_TextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Forgot_Password_Button, ui_event_Forgot_Password_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSend, ui_event_ButtonSend, LV_EVENT_ALL, NULL);
}
