// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Discord Login
#include "ui/ui.h"

void ui_Setting_Screen_screen_init(void)
{
    ui_Setting_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Setting_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Setting_Screen, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Right_Panel = lv_obj_create(ui_Setting_Screen);
    lv_obj_set_width(ui_Setting_Right_Panel, lv_pct(40));
    lv_obj_set_height(ui_Setting_Right_Panel, lv_pct(99));
    lv_obj_set_x(ui_Setting_Right_Panel, -2);
    lv_obj_set_y(ui_Setting_Right_Panel, 0);
    lv_obj_set_align(ui_Setting_Right_Panel, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Setting_Right_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Setting_Right_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_Right_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Setting_Right_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Setting_Right_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Right_Panel_Container = lv_obj_create(ui_Setting_Right_Panel);
    lv_obj_remove_style_all(ui_Setting_Right_Panel_Container);
    lv_obj_set_width(ui_Setting_Right_Panel_Container, lv_pct(119));
    lv_obj_set_height(ui_Setting_Right_Panel_Container, lv_pct(117));
    lv_obj_set_align(ui_Setting_Right_Panel_Container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Setting_Right_Panel_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(ui_Setting_Right_Panel_Container, lv_color_hex(0xB2B2B4),
                              LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_Right_Panel_Container, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Setting_Right_Panel_Header_Label = lv_label_create(ui_Setting_Right_Panel_Container);
    lv_obj_set_width(ui_Setting_Right_Panel_Header_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Setting_Right_Panel_Header_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Right_Panel_Header_Label, 0);
    lv_obj_set_y(ui_Setting_Right_Panel_Header_Label, 40);
    lv_obj_set_align(ui_Setting_Right_Panel_Header_Label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Setting_Right_Panel_Header_Label, "Setting");
    lv_obj_set_style_text_font(ui_Setting_Right_Panel_Header_Label, &ui_font_gg_sans_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Right_Panel_WiFi_Button = lv_btn_create(ui_Setting_Right_Panel_Container);
    lv_obj_set_height(ui_Setting_Right_Panel_WiFi_Button, 40);
    lv_obj_set_width(ui_Setting_Right_Panel_WiFi_Button, lv_pct(100));
    lv_obj_set_align(ui_Setting_Right_Panel_WiFi_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Setting_Right_Panel_WiFi_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Setting_Right_Panel_WiFi_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Setting_Right_Panel_WiFi_Button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_Right_Panel_WiFi_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Setting_Right_Panel_WiFi_Button, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Setting_Right_Panel_WiFi_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Right_Panel_WiFi_Button_Icon = lv_img_create(ui_Setting_Right_Panel_WiFi_Button);
    lv_img_set_src(ui_Setting_Right_Panel_WiFi_Button_Icon, &ui_img_592994106);
    lv_obj_set_width(ui_Setting_Right_Panel_WiFi_Button_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Setting_Right_Panel_WiFi_Button_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Right_Panel_WiFi_Button_Icon, 5);
    lv_obj_set_y(ui_Setting_Right_Panel_WiFi_Button_Icon, 0);
    lv_obj_set_align(ui_Setting_Right_Panel_WiFi_Button_Icon, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Setting_Right_Panel_WiFi_Button_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Setting_Right_Panel_WiFi_Button_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Setting_Right_Panel_WiFi_Button_Label = lv_label_create(ui_Setting_Right_Panel_WiFi_Button);
    lv_obj_set_width(ui_Setting_Right_Panel_WiFi_Button_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Setting_Right_Panel_WiFi_Button_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Right_Panel_WiFi_Button_Label, -38);
    lv_obj_set_y(ui_Setting_Right_Panel_WiFi_Button_Label, -5);
    lv_obj_set_align(ui_Setting_Right_Panel_WiFi_Button_Label, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Setting_Right_Panel_WiFi_Button_Label, "Wi-Fi");
    lv_obj_set_style_text_color(ui_Setting_Right_Panel_WiFi_Button_Label, lv_color_hex(0x151517),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Right_Panel_WiFi_Button_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Right_Panel_WiFi_Button_Label, &ui_font_gg_sans_small,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Right_Panel_WiFi_Button_Description_Label = lv_label_create(ui_Setting_Right_Panel_WiFi_Button);
    lv_obj_set_width(ui_Setting_Right_Panel_WiFi_Button_Description_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Setting_Right_Panel_WiFi_Button_Description_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Right_Panel_WiFi_Button_Description_Label, -38);
    lv_obj_set_y(ui_Setting_Right_Panel_WiFi_Button_Description_Label, 10);
    lv_obj_set_align(ui_Setting_Right_Panel_WiFi_Button_Description_Label, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Setting_Right_Panel_WiFi_Button_Description_Label, "Connect To New Wi-Fi");
    lv_obj_set_style_text_color(ui_Setting_Right_Panel_WiFi_Button_Description_Label, lv_color_hex(0xB2B2B4),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Right_Panel_WiFi_Button_Description_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Right_Panel_WiFi_Button_Description_Label, &ui_font_gg_sans_small,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Right_Panel_Bot_Info_Button = lv_btn_create(ui_Setting_Right_Panel_Container);
    lv_obj_set_height(ui_Setting_Right_Panel_Bot_Info_Button, 40);
    lv_obj_set_width(ui_Setting_Right_Panel_Bot_Info_Button, lv_pct(100));
    lv_obj_set_x(ui_Setting_Right_Panel_Bot_Info_Button, 0);
    lv_obj_set_y(ui_Setting_Right_Panel_Bot_Info_Button, 45);
    lv_obj_set_align(ui_Setting_Right_Panel_Bot_Info_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Setting_Right_Panel_Bot_Info_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Setting_Right_Panel_Bot_Info_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Setting_Right_Panel_Bot_Info_Button, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_Right_Panel_Bot_Info_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Setting_Right_Panel_Bot_Info_Button, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Setting_Right_Panel_Bot_Info_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Right_Panel_Bot_Info_Button_Icon = lv_img_create(ui_Setting_Right_Panel_Bot_Info_Button);
    lv_img_set_src(ui_Setting_Right_Panel_Bot_Info_Button_Icon, &ui_img_2024208504);
    lv_obj_set_width(ui_Setting_Right_Panel_Bot_Info_Button_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Setting_Right_Panel_Bot_Info_Button_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Right_Panel_Bot_Info_Button_Icon, 5);
    lv_obj_set_y(ui_Setting_Right_Panel_Bot_Info_Button_Icon, 0);
    lv_obj_set_align(ui_Setting_Right_Panel_Bot_Info_Button_Icon, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Setting_Right_Panel_Bot_Info_Button_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Setting_Right_Panel_Bot_Info_Button_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Setting_Right_Panel_Bot_Info_Button_Label = lv_label_create(ui_Setting_Right_Panel_Bot_Info_Button);
    lv_obj_set_width(ui_Setting_Right_Panel_Bot_Info_Button_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Setting_Right_Panel_Bot_Info_Button_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Right_Panel_Bot_Info_Button_Label, -38);
    lv_obj_set_y(ui_Setting_Right_Panel_Bot_Info_Button_Label, -5);
    lv_obj_set_align(ui_Setting_Right_Panel_Bot_Info_Button_Label, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Setting_Right_Panel_Bot_Info_Button_Label, "Bot Info");
    lv_obj_set_style_text_color(ui_Setting_Right_Panel_Bot_Info_Button_Label, lv_color_hex(0x151517),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Right_Panel_Bot_Info_Button_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Right_Panel_Bot_Info_Button_Label, &ui_font_gg_sans_small,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Right_Panel_Bot_Info_Button_Description_Label = lv_label_create(ui_Setting_Right_Panel_Bot_Info_Button);
    lv_obj_set_width(ui_Setting_Right_Panel_Bot_Info_Button_Description_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Setting_Right_Panel_Bot_Info_Button_Description_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Right_Panel_Bot_Info_Button_Description_Label, -38);
    lv_obj_set_y(ui_Setting_Right_Panel_Bot_Info_Button_Description_Label, 10);
    lv_obj_set_align(ui_Setting_Right_Panel_Bot_Info_Button_Description_Label, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Setting_Right_Panel_Bot_Info_Button_Description_Label, "See & Change Bot Info");
    lv_obj_set_style_text_color(ui_Setting_Right_Panel_Bot_Info_Button_Description_Label, lv_color_hex(0xB2B2B4),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Right_Panel_Bot_Info_Button_Description_Label, 255,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Right_Panel_Bot_Info_Button_Description_Label, &ui_font_gg_sans_small,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Right_Panel_Info_Button = lv_btn_create(ui_Setting_Right_Panel_Container);
    lv_obj_set_height(ui_Setting_Right_Panel_Info_Button, 40);
    lv_obj_set_width(ui_Setting_Right_Panel_Info_Button, lv_pct(100));
    lv_obj_set_x(ui_Setting_Right_Panel_Info_Button, 0);
    lv_obj_set_y(ui_Setting_Right_Panel_Info_Button, 90);
    lv_obj_set_align(ui_Setting_Right_Panel_Info_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Setting_Right_Panel_Info_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Setting_Right_Panel_Info_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Setting_Right_Panel_Info_Button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_Right_Panel_Info_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Setting_Right_Panel_Info_Button, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Setting_Right_Panel_Info_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Right_Panel_Info_Button_Icon = lv_img_create(ui_Setting_Right_Panel_Info_Button);
    lv_img_set_src(ui_Setting_Right_Panel_Info_Button_Icon, &ui_img_1746740777);
    lv_obj_set_width(ui_Setting_Right_Panel_Info_Button_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Setting_Right_Panel_Info_Button_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Right_Panel_Info_Button_Icon, 7);
    lv_obj_set_y(ui_Setting_Right_Panel_Info_Button_Icon, 3);
    lv_obj_set_align(ui_Setting_Right_Panel_Info_Button_Icon, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Setting_Right_Panel_Info_Button_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Setting_Right_Panel_Info_Button_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Setting_Right_Panel_Info_Button_Label = lv_label_create(ui_Setting_Right_Panel_Info_Button);
    lv_obj_set_width(ui_Setting_Right_Panel_Info_Button_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Setting_Right_Panel_Info_Button_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Right_Panel_Info_Button_Label, -38);
    lv_obj_set_y(ui_Setting_Right_Panel_Info_Button_Label, -5);
    lv_obj_set_align(ui_Setting_Right_Panel_Info_Button_Label, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Setting_Right_Panel_Info_Button_Label, "About Us");
    lv_obj_set_style_text_color(ui_Setting_Right_Panel_Info_Button_Label, lv_color_hex(0x151517),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Right_Panel_Info_Button_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Right_Panel_Info_Button_Label, &ui_font_gg_sans_small,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Right_Panel_Info_Button_Description_Label = lv_label_create(ui_Setting_Right_Panel_Info_Button);
    lv_obj_set_width(ui_Setting_Right_Panel_Info_Button_Description_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Setting_Right_Panel_Info_Button_Description_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Right_Panel_Info_Button_Description_Label, -38);
    lv_obj_set_y(ui_Setting_Right_Panel_Info_Button_Description_Label, 10);
    lv_obj_set_align(ui_Setting_Right_Panel_Info_Button_Description_Label, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Setting_Right_Panel_Info_Button_Description_Label, "Project Information");
    lv_obj_set_style_text_color(ui_Setting_Right_Panel_Info_Button_Description_Label, lv_color_hex(0xB2B2B4),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Right_Panel_Info_Button_Description_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Right_Panel_Info_Button_Description_Label, &ui_font_gg_sans_small,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Left_Panel = lv_obj_create(ui_Setting_Screen);
    lv_obj_set_width(ui_Setting_Left_Panel, lv_pct(60));
    lv_obj_set_height(ui_Setting_Left_Panel, lv_pct(100));
    lv_obj_set_align(ui_Setting_Left_Panel, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Setting_Left_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Setting_Left_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_Left_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Setting_Left_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Setting_Left_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Left_Panel_WiFi_Panel = lv_obj_create(ui_Setting_Left_Panel);
    lv_obj_set_width(ui_Setting_Left_Panel_WiFi_Panel, lv_pct(110));
    lv_obj_set_height(ui_Setting_Left_Panel_WiFi_Panel, lv_pct(110));
    lv_obj_set_align(ui_Setting_Left_Panel_WiFi_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Setting_Left_Panel_WiFi_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Setting_Left_Panel_WiFi_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_Left_Panel_WiFi_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Setting_Left_Panel_WiFi_Panel, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Setting_Left_Panel_WiFi_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Left_Panel_WiFi_Panel_Label = lv_label_create(ui_Setting_Left_Panel_WiFi_Panel);
    lv_obj_set_width(ui_Setting_Left_Panel_WiFi_Panel_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Setting_Left_Panel_WiFi_Panel_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Left_Panel_WiFi_Panel_Label, 5);
    lv_obj_set_y(ui_Setting_Left_Panel_WiFi_Panel_Label, -5);
    lv_obj_set_align(ui_Setting_Left_Panel_WiFi_Panel_Label, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Setting_Left_Panel_WiFi_Panel_Label, "Wi-Fi");
    lv_obj_set_style_text_color(ui_Setting_Left_Panel_WiFi_Panel_Label, lv_color_hex(0x151517),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Left_Panel_WiFi_Panel_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Left_Panel_WiFi_Panel_Label, &ui_font_gg_sans_small,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel = lv_obj_create(ui_Setting_Left_Panel_WiFi_Panel);
    lv_obj_set_width(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel, 302);
    lv_obj_set_height(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel, 40);
    lv_obj_set_x(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel, 2);
    lv_obj_set_y(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel, 16);
    lv_obj_set_align(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel, lv_color_hex(0xF2F2F2),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel, 0,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle = lv_switch_create(
                                                            ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel);
    lv_obj_set_width(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle, 62);
    lv_obj_set_height(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle, 30);
    lv_obj_set_x(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle, -13);
    lv_obj_set_y(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle, 0);
    lv_obj_set_align(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle, LV_ALIGN_LEFT_MID);
    lv_obj_add_state(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle, LV_STATE_CHECKED);       /// States


    ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel_Label = lv_label_create(
                                                                        ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel);
    lv_obj_set_width(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel_Label, 3);
    lv_obj_set_y(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel_Label, 0);
    lv_obj_set_align(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel_Label, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel_Label, "Wi-Fi On");
    lv_obj_set_style_text_color(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel_Label, lv_color_hex(0x151517),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel_Label, 255,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle_Panel_Label, &ui_font_gg_sans_small,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Left_Panel_Bot_Info_Panel = lv_obj_create(ui_Setting_Left_Panel);
    lv_obj_set_width(ui_Setting_Left_Panel_Bot_Info_Panel, lv_pct(110));
    lv_obj_set_height(ui_Setting_Left_Panel_Bot_Info_Panel, lv_pct(110));
    lv_obj_set_align(ui_Setting_Left_Panel_Bot_Info_Panel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Setting_Left_Panel_Bot_Info_Panel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Setting_Left_Panel_Bot_Info_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Setting_Left_Panel_Bot_Info_Panel, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_Left_Panel_Bot_Info_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Setting_Left_Panel_Bot_Info_Panel, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Setting_Left_Panel_Bot_Info_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Left_Panel_Bot_Info_Panel_Label = lv_label_create(ui_Setting_Left_Panel_Bot_Info_Panel);
    lv_obj_set_width(ui_Setting_Left_Panel_Bot_Info_Panel_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Setting_Left_Panel_Bot_Info_Panel_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Left_Panel_Bot_Info_Panel_Label, 5);
    lv_obj_set_y(ui_Setting_Left_Panel_Bot_Info_Panel_Label, -5);
    lv_obj_set_align(ui_Setting_Left_Panel_Bot_Info_Panel_Label, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Setting_Left_Panel_Bot_Info_Panel_Label, "Bot Info");
    lv_obj_set_style_text_color(ui_Setting_Left_Panel_Bot_Info_Panel_Label, lv_color_hex(0x151517),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Left_Panel_Bot_Info_Panel_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Left_Panel_Bot_Info_Panel_Label, &ui_font_gg_sans_small,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Left_Panel_About_Us_Panel = lv_obj_create(ui_Setting_Left_Panel);
    lv_obj_set_width(ui_Setting_Left_Panel_About_Us_Panel, lv_pct(110));
    lv_obj_set_height(ui_Setting_Left_Panel_About_Us_Panel, lv_pct(110));
    lv_obj_set_align(ui_Setting_Left_Panel_About_Us_Panel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Setting_Left_Panel_About_Us_Panel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Setting_Left_Panel_About_Us_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Setting_Left_Panel_About_Us_Panel, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_Left_Panel_About_Us_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Setting_Left_Panel_About_Us_Panel, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Setting_Left_Panel_About_Us_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Left_Panel_About_Us_Panel_Label = lv_label_create(ui_Setting_Left_Panel_About_Us_Panel);
    lv_obj_set_width(ui_Setting_Left_Panel_About_Us_Panel_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Setting_Left_Panel_About_Us_Panel_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Setting_Left_Panel_About_Us_Panel_Label, 5);
    lv_obj_set_y(ui_Setting_Left_Panel_About_Us_Panel_Label, -5);
    lv_obj_set_align(ui_Setting_Left_Panel_About_Us_Panel_Label, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Setting_Left_Panel_About_Us_Panel_Label, "About Us");
    lv_obj_set_style_text_color(ui_Setting_Left_Panel_About_Us_Panel_Label, lv_color_hex(0x151517),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Setting_Left_Panel_About_Us_Panel_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Setting_Left_Panel_About_Us_Panel_Label, &ui_font_gg_sans_small,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setting_Keyboard = lv_keyboard_create(ui_Setting_Screen);
    lv_obj_set_width(ui_Setting_Keyboard, lv_pct(100));
    lv_obj_set_height(ui_Setting_Keyboard, lv_pct(60));
    lv_obj_set_align(ui_Setting_Keyboard, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Setting_Keyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_Setting_Right_Panel_WiFi_Button, ui_event_Setting_Right_Panel_WiFi_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_Right_Panel_Bot_Info_Button, ui_event_Setting_Right_Panel_Bot_Info_Button, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_Setting_Right_Panel_Info_Button, ui_event_Setting_Right_Panel_Info_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle,
                        ui_event_Setting_Left_Panel_WiFi_Panel_On_Or_Off_Toggle, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_Screen, ui_event_Setting_Screen, LV_EVENT_ALL, NULL);

}
